server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password:
    url: jdbc:mysql://localhost:3306/billing
    username: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: false
springdoc:
  api-docs:
    path: billing-docs