server:
  port: 8082
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: Yondaime2650
    url: jdbc:postgresql://localhost:5432/billing
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: false